import groovy.transform.Field

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'rusty-report-printer'

pipeline {
    agent {
        kubernetes {
        inheritFrom 'Node16Alpine'
            defaultContainer 'rust'
            yamlMergeStrategy merge()
            yaml '''
              spec:
                containers:
                    - name: rust
                      image: rustlang/rust:nightly-alpine
                      command: ["sleep", "infinity"]
                      resources:
                        requests:
                            cpu: 100m
                            memory: 256Mi
                        limits:
                            cpu: 2
                            memory: 256Mi
                    - name: kaniko
                      image: gcr.io/kaniko-project/executor:v1.8.1-debug
                      command: ["sleep", "infinity"]
                      resources:
                        requests:
                            cpu: 100m
                            memory: 515Mi
                        limits:
                            cpu: 2
                            memory: 1Gi
            '''
        }
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                    container('node16') {
                        sh './report_generator.js'
                    }
                }
            }
        }

       stage('Install dependencies') {
           steps {
               dir(PROJECT_DIR) {
                   // if we are on alpine, we need to install musl-dev
                   sh 'apk add --no-cache musl-dev=1.2.2-r7'
               }
           }
       }

        stage('Build') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'cargo build --locked'
                }
            }
        }

        // Oh no, we can't perform regular Docker Builds on Kubernetes

        stage('Build Image') {
            steps {
                dir(PROJECT_DIR) {
                    container('kaniko') {
                        sh '''/kaniko/executor --context=. \\
                          --dockerfile=./Dockerfile \\
                          --destination=rust-report-printer:v0.1.0 \\
                          --no-push
                        '''
                    }
                }
            }
        }

    }
}
