import groovy.transform.Field

library 'jenkins-tutorial-shared-lib'

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'rusty-report-printer'

pipeline {
    agent {
        kubernetes {
        inheritFrom 'Node16Alpine Kaniko'
            defaultContainer 'rust'
            yamlMergeStrategy merge()
            yaml '''
            spec:
                containers:
                    - name: rust
                      image: rustlang/rust:nightly-alpine
                      command: ["sleep", "infinity"]
                      resources:
                        requests:
                            cpu: 100m
                            memory: 256Mi
                        limits:
                            cpu: 2
                            memory: 256Mi
            '''
        }
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                    container('node16') {
                        sh './report_generator.js'
                    }
                }
            }
        }

       stage('Install dependencies') {
           steps {
               dir(PROJECT_DIR) {
                   // if we are on alpine, we need to install musl-dev
                   sh 'apk add --no-cache musl-dev=1.2.2-r7'
               }
           }
       }

        stage('Build') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'cargo build --locked'
                }
            }
        }

        // Oh no, we can't perform regular Docker Builds on Kubernetes

        stage('Build Image') {
            steps {
                dir(PROJECT_DIR) {
                   scrip{
                       kaniko.buildNoPush imageName: 'rust-report-printer',
                                          imageTag: getImageTags(),
                                          context: PROJECT_DIR,
                                          dockerfile: "${PROJECT_DIR}/Dockerfile",
                                          extraArgs: '--user-new-run --snapshotMode=redo'

                   }
                }
            }
        }
    }
}

def getImageTags(){
    def commitTag: = [sanitizeImageTag("${env.GIT_BRANCH}-${env.GIT_COMMIT}")]

    if (isMaster(){
        commitTag += 'latest'
    }
    return tags
}