import groovy.transform.Field
library 'jenkins-tutorial-shared-lib'
// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'super-report-printer'

pipeline {
    agent {
        kubernetes {
            inheritFrom 'Node16Alpine Kaniko'
            defaultContainer 'node16'
            yamlMergeStrategy merge()
            yaml '''
            spec:
              containers:
                - name: python
                  image: python:3.10-alpine3.16
                  command: ["sleep", "infinity"]
                  resources:
                    requests:
                      cpu: 10m
                      memory: 16Mi
                    limits:
                      cpu: 1
                      memory: 16Mi
                - name: kaniko
                  image: gcr.io/kaniko-project/executor:v1.8.1-debug
                  command: ["sleep", "infinity"]
                  resources:
                    requests:
                      cpu: 100m
                      memory: 515Mi
                    limits:
                      cpu: 2
                      memory: 1Gi
            '''
        }
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                    container('python') {
                        sh './report_generator.py'
                    }
                }
            }
        }

        stage('Install dependencies') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm ci'
                }
            }
        }

        stage('Build Typescript') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm run build'
                }
            }
        }


        stage('Build Image') {
            steps {
                dir(PROJECT_DIR) {
                kaniko.buildNoPush(
                    imageName: 'super-report-printer',
                    imageTag: getImageTags(),
                    context: '.',
                    dockerfile: './Dockerfile',
                    extraArgs: '--user-new-run --snapshotMode=redo'
                )

                }
            }
        }
    }
}
def getImageTags(){
    def commitTag: = sanitizeImageTag("{env.GIT_BRANCH.replace('/', '-')}-${env.GIT_COMMIT}")
    def tags:ArrayList = [commitTag]

    if (isMaster(){
    tags += 'latest'
    }
    return tags
