import groovy.transform.Field

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'super-report-printer'

pipeline {
    agent {
        kubernetes {
            inheritFrom 'Node16Alpine'
            defaultContainer 'node16'
            yamlMergeStrategy merge()
            yaml '''
            spec:
              containers:
                - name: python
                  image: python:3.10-alpine3.16
                  command: ["sleep", "infinity"]
                  resources:
                    requests:
                      cpu: 10m
                      memory: 16Mi
                    limits:
                      cpu: 1
                      memory: 16Mi
                - name: kaniko
                  image: gcr.io/kaniko-project/executor:v1.8.1-debug
                  command: ["sleep", "infinity"]
                  resources:
                    requests:
                      cpu: 100m
                      memory: 515Mi
                    limits:
                      cpu: 2
                      memory: 1Gi
            '''
        }
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                    container('python') {
                        sh './report_generator.py'
                    }
                }
            }
        }

        stage('Install dependencies') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm ci'
                }
            }
        }

        stage('Build Typescript') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm run build'
                }
            }
        }


        stage('Build Image') {
            steps {
                dir(PROJECT_DIR) {
                    container('kaniko'){
                        // Kaniko shell
                        sh '''/kaniko/executor --context=. \\
                          --dockerfile=./Dockerfile \\
                          --destination=super-report-printer:v0.1.0 \\
                          --no-push
                        '''
                    }
                }
            }
        }
    }
}
